network: Mainnet
containerOutDir: /Users/doomsower/projects/gearbox/liquidator-v2/apps/optimist/output
hostOutDir: /Users/doomsower/projects/gearbox/liquidator-v2/apps/optimist/output
originRPC: "${sm.ANVIL_NODE.chainstack_ethereum}"
logLevel: debug
ghcrCredentials:
  username: "${sm.ANVIL_NODE.githubUser}"
  password: "${sm.ANVIL_NODE.githubToken}"
# s3Bucket:
# s3Prefix:
# grafanaDashboardURL:
extraMessage: "[LOCAL-DEV]"

liquidators:
  - id: ts
    name: "TS Full"
    group: "full"
    imageTag: beta
    rpc: "${sm.ANVIL_NODE.chainstack_ethereum}"
    env:
      LIQUIDATOR_ADDRESS: "0x185E17894F5716753F857129C98E2BCCEd7e36FD"
    setup:
      emergencyMode: true
      zeroLT: true

  - id: wallet
    name: "Wallet"
    imageTag: beta
    rpc: "${sm.ANVIL_NODE.chainstack_ethereum}"
    env:
      LIQUIDATION_MODE: "full"
      STRATEGY: "wallet"
      LIQUIDATOR_ADDRESS: "0x185E17894F5716753F857129C98E2BCCEd7e36FD"
    setup:
      zeroLT: true
      fundUnderlying: true
      # admins are impersonated on the fork, they must hold the corresponding role
      # kyc:
      #   midasAdmin: "0x..."
      #   securitizeAdmin: "0x..."
