// const ADD_COLLATERAL_PERMISSION = 1n << 0n;
// const INCREASE_DEBT_PERMISSION = 1n << 1n;
const DECREASE_DEBT_PERMISSION = 1n << 2n;
const WITHDRAW_COLLATERAL_PERMISSION = 1n << 5n;
// const UPDATE_QUOTA_PERMISSION = 1n << 6n;
// const SET_BOT_PERMISSIONS_PERMISSION = 1n << 8n;
// const EXTERNAL_CALLS_PERMISSION = 1n << 16n;

export const DELEVERAGE_PERMISSIONS =
  DECREASE_DEBT_PERMISSION | WITHDRAW_COLLATERAL_PERMISSION;
