name: Check PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  HUSKY: 0
  CI: true

jobs:
  checks:
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v2
        with:
          cache: true
          require-lockfile: true

      - name: Perform checks
        run: |
          pnpm typecheck:ci
          pnpm check:ci
