name: Check PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  HUSKY: 0
  CI: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Perform checks
        run: |
          pnpm install --frozen-lockfile
          pnpm typecheck:ci
          pnpm check:ci
